# Generated by Django 5.0.2 on 2024-10-13 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingoption',
            name='print_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='printingoption',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printing_options', to='reservations.servicetype'),
        ),
    ]
