# Generated by Django 5.0.2 on 2024-10-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcrental',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='printingoption',
            name='service_type',
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.TextField(blank=True, help_text='Any additional needs or requests from the customer', null=True),
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
